### ISSUE TITLE
Exception while reading contacts

### ISSUE THREAD

**Issue by kanvuduc** [AppLozic/Applozic-Android-Chat-Sample#4]
While I run the sample app on my device.

```
E/SQLiteDatabase: Error inserting connected=0 userTypeId=null fullName=B Dangsource contactType=1 applozicType=0 userId=lkupkey-1444i4a9867b88f7f1b0 deletedAtTime=0 contactNO=+1912584504 status=null phoneContactDisplayName=B Dangsource
                                                                       android.database.sqlite.SQLiteException: table contact has no column named applozicType (code 1): , while compiling: INSERT INTO contact(connected,userTypeId,fullName,contactType,applozicType,userId,deletedAtTime,contactNO,status,phoneContactDisplayName) VALUES (?,?,?,?,?,?,?,?,?,?)
                                                                           at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                           at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                           at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                           at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                           at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                           at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                           at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1472)
                                                                           at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
                                                                           at com.applozic.mobicomkit.contact.database.ContactDatabase.addContact(ContactDatabase.java:231)
                                                                           at com.applozic.mobicomkit.contact.AppContactService.upsert(AppContactService.java:94)
                                                                           at com.applozic.mobicomkit.uiwidgets.people.contact.DeviceContactSyncService.process(DeviceContactSyncService.java:83)
                                                                           at com.applozic.mobicomkit.uiwidgets.people.contact.DeviceContactSyncService.access$100(DeviceContactSyncService.java:23)
                                                                           at com.applozic.mobicomkit.uiwidgets.people.cont
```

**Comment by Sunilkumarr** [comment]
Did you installed apk from another github repo and  then you installed from device contacts sdk ? can you uninstall old apk  and install  and let me know if you still face this issue  ?

**Comment by kanvuduc** [comment]
I run your latest code here.

**Comment by Sunilkumarr** [comment]
can you uninstall old apk which you have installed before in your  device and install fresh new apk from android studio ,  this is the case if you have installed a apk with same DB version   then your updating new apk from device contacts sdk

**Comment by kanvuduc** [comment]
Oh, it works. Thanks.
